import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import jsxA11y from 'eslint-plugin-jsx-a11y'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      'dist',
      'coverage',
      // Generated by `npm run icons`. Never hand-edited. CLAUDE.md §3.
      'src/components/icon/registry.generated.ts',
      'src/components/icon/registry.names.generated.ts',
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      // CLAUDE.md §6.
      '@typescript-eslint/no-explicit-any': 'error',
      'no-console': 'error',

      // CLAUDE.md §3: one <Icon> component is the only way an icon reaches a
      // screen. No raw <svg> in feature code, no direct imports from assets.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/assets/icons/*', '@/assets/icons/*'],
              message:
                'Import icons through <Icon name="category/name" />, never directly. CLAUDE.md §3.',
            },
            {
              group: ['**/assets/icons-generated/*', '@/assets/icons-generated/*'],
              message:
                'icons-generated/ is a build artefact. Use <Icon name="category/name" />. CLAUDE.md §3.',
            },
          ],
        },
      ],

      // CLAUDE.md §6: no localStorage/sessionStorage for record data.
      'no-restricted-globals': [
        'error',
        {
          name: 'localStorage',
          message: 'No localStorage for record data — in-memory only. CLAUDE.md §6.',
        },
        {
          name: 'sessionStorage',
          message: 'No sessionStorage for record data — in-memory only. CLAUDE.md §6.',
        },
      ],
    },
  },
  {
    // Thin wrappers re-export the Radix parts they do not need to restyle —
    // Popover.Root, Tabs.Root and so on — alongside the parts they do. That
    // is what "thin wrapper" means (PRD §3.2), and it costs only HMR
    // granularity in these files. MarCell additionally exports
    // marCellDescription so the Phase 3 MAR table can put the full-sentence
    // accessible name on its <td> directly.
    files: ['src/components/primitives/**/*.tsx', 'src/components/status/MarCell.tsx'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
  {
    // Node-side build scripts.
    files: ['scripts/**/*.mjs'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: globals.node,
    },
    rules: {
      // Build scripts report to the terminal; that is their entire job.
      'no-console': 'off',
    },
  },
  {
    files: ['**/*.test.{ts,tsx}', 'src/test/**/*.ts'],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
  },
)
